const { requireDb }=require('../utils/db.util');
async function list({whereSql='1=1',params=[],filters={},limit=25,offset=0},conn=requireDb()){
  const where=[whereSql]; const p=[...params];
  if(filters.category_id){where.push('c.category_id=?');p.push(filters.category_id);} if(filters.is_active!==undefined){where.push('c.is_active=?');p.push(filters.is_active);} if(filters.search){where.push('(c.consumable_code LIKE ? OR c.name LIKE ? OR c.variant LIKE ?)');const q=`%${filters.search}%`;p.push(q,q,q);} const w=where.join(' AND ');
  const [[count]]=await conn.query(`SELECT COUNT(*) total FROM consumables c WHERE ${w}`,p);
  const [rows]=await conn.query(`SELECT c.*,mc.name category_name,mb.name brand_name,u.code uom_code,u.name uom_name,COALESCE(SUM(b.quantity),0) total_stock FROM consumables c JOIN master_categories mc ON mc.id=c.category_id LEFT JOIN master_brands mb ON mb.id=c.brand_id JOIN master_uoms u ON u.id=c.uom_id LEFT JOIN consumable_stock_balances b ON b.consumable_id=c.id WHERE ${w} GROUP BY c.id ORDER BY c.id DESC LIMIT ? OFFSET ?`,[...p,limit,offset]); return {rows,total:count.total};
}
async function get(id,conn=requireDb(),forUpdate=false){let sql=`SELECT c.*,mc.name category_name,mc.tracking_type,mb.name brand_name,u.code uom_code,u.name uom_name FROM consumables c JOIN master_categories mc ON mc.id=c.category_id LEFT JOIN master_brands mb ON mb.id=c.brand_id JOIN master_uoms u ON u.id=c.uom_id WHERE c.id=? LIMIT 1`;if(forUpdate)sql+=' FOR UPDATE';const [r]=await conn.query(sql,[id]);return r[0]||null;}
async function create(data,conn=requireDb()){const [r]=await conn.query(`INSERT INTO consumables (consumable_code,name,category_id,brand_id,variant,uom_id,managing_department_id,company_id,minimum_stock,notes,is_active,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[data.consumable_code,data.name,data.category_id,data.brand_id||null,data.variant||null,data.uom_id,data.managing_department_id,data.company_id,data.minimum_stock||0,data.notes||null,data.is_active===false?0:1,data.created_by||null,data.created_by||null]);return r.insertId;}
async function update(id,data,conn=requireDb()){const fields=['name','category_id','brand_id','variant','uom_id','minimum_stock','notes','is_active','updated_by'];const set=[];const p=[];for(const f of fields){if(data[f]!==undefined){set.push(`${f}=?`);p.push(data[f]);}}if(set.length){p.push(id);await conn.query(`UPDATE consumables SET ${set.join(',')} WHERE id=?`,p);}}
async function balances(id,conn=requireDb()){const [r]=await conn.query(`SELECT b.*,l.code location_code,l.name location_name FROM consumable_stock_balances b JOIN master_locations l ON l.id=b.location_id WHERE b.consumable_id=? ORDER BY l.name`,[id]);return r;}
async function transactions(id,conn=requireDb()){const [r]=await conn.query(`SELECT t.*,fl.name from_location_name,tl.name to_location_name,a.asset_number recipient_asset_number FROM consumable_stock_transactions t LEFT JOIN master_locations fl ON fl.id=t.from_location_id LEFT JOIN master_locations tl ON tl.id=t.to_location_id LEFT JOIN assets a ON a.id=t.recipient_asset_id WHERE t.consumable_id=? ORDER BY t.transaction_date DESC,t.id DESC`,[id]);return r;}
async function lockBalance(consumableId,locationId,conn){await conn.query(`INSERT INTO consumable_stock_balances (consumable_id,location_id,quantity) VALUES (?,?,0) ON DUPLICATE KEY UPDATE quantity=quantity`,[consumableId,locationId]);const [r]=await conn.query(`SELECT * FROM consumable_stock_balances WHERE consumable_id=? AND location_id=? FOR UPDATE`,[consumableId,locationId]);return r[0];}
async function setBalance(consumableId,locationId,quantity,conn){await conn.query('UPDATE consumable_stock_balances SET quantity=? WHERE consumable_id=? AND location_id=?',[quantity,consumableId,locationId]);}
async function createTransaction(data,conn=requireDb()){const [r]=await conn.query(`INSERT INTO consumable_stock_transactions (transaction_number,consumable_id,movement_type,from_location_id,to_location_id,quantity,unit_cost,recipient_type,recipient_user_id,recipient_user_name_snapshot,recipient_department_id,recipient_department_name_snapshot,recipient_asset_id,recipient_location_id,purpose,reference_number,notes,transaction_date,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[data.transaction_number,data.consumable_id,data.movement_type,data.from_location_id||null,data.to_location_id||null,data.quantity,data.unit_cost??null,data.recipient_type||null,data.recipient_user_id||null,data.recipient_user_name_snapshot||null,data.recipient_department_id||null,data.recipient_department_name_snapshot||null,data.recipient_asset_id||null,data.recipient_location_id||null,data.purpose||null,data.reference_number||null,data.notes||null,data.transaction_date,data.created_by]);return r.insertId;}
async function getTransaction(id,conn=requireDb()){const [r]=await conn.query('SELECT * FROM consumable_stock_transactions WHERE id=?',[id]);return r[0]||null;}
module.exports={list,get,create,update,balances,transactions,lockBalance,setBalance,createTransaction,getTransaction};
