const { requireDb }=require('../utils/db.util');
async function listPolicies(whereSql='1=1',params=[],conn=requireDb()){const [r]=await conn.query(`SELECT * FROM depreciation_policies p WHERE ${whereSql} ORDER BY p.id DESC`,params);return r;}
async function getPolicy(id,conn=requireDb(),forUpdate=false){let sql='SELECT * FROM depreciation_policies WHERE id=? LIMIT 1';if(forUpdate)sql+=' FOR UPDATE';const [r]=await conn.query(sql,[id]);return r[0]||null;}
async function createPolicy(data,conn=requireDb()){const [r]=await conn.query(`INSERT INTO depreciation_policies (managing_department_id,company_id,name,method,useful_life_months,salvage_value_type,salvage_value,is_active,created_by) VALUES (?,?,?,?,?,?,?,?,?)`,[data.managing_department_id,data.company_id||null,data.name,data.method||'STRAIGHT_LINE',data.useful_life_months,data.salvage_value_type||'FIXED',data.salvage_value||0,data.is_active===false?0:1,data.created_by||null]);return r.insertId;}
async function updatePolicy(id,data,conn=requireDb()){const fields=['name','method','useful_life_months','salvage_value_type','salvage_value','is_active'];const set=[];const p=[];for(const f of fields){if(data[f]!==undefined){set.push(`${f}=?`);p.push(data[f]);}}if(set.length){p.push(id);await conn.query(`UPDATE depreciation_policies SET ${set.join(',')} WHERE id=?`,p);}}
async function setCategoryDefault(data,conn=requireDb()){await conn.query('DELETE FROM category_depreciation_defaults WHERE category_id=? AND managing_department_id=? AND ((company_id IS NULL AND ? IS NULL) OR company_id=?)',[data.category_id,data.managing_department_id,data.company_id||null,data.company_id||null]);await conn.query(`INSERT INTO category_depreciation_defaults (category_id,managing_department_id,company_id,depreciation_policy_id) VALUES (?,?,?,?)`,[data.category_id,data.managing_department_id,data.company_id||null,data.depreciation_policy_id]);}
async function getCategoryDefault(categoryId,departmentId,companyId,conn=requireDb()){const [r]=await conn.query(`SELECT d.*,p.name policy_name,p.method,p.useful_life_months,p.salvage_value_type,p.salvage_value FROM category_depreciation_defaults d JOIN depreciation_policies p ON p.id=d.depreciation_policy_id WHERE d.category_id=? AND d.managing_department_id=? AND (d.company_id=? OR d.company_id IS NULL) AND p.is_active=1 ORDER BY (d.company_id IS NOT NULL) DESC,d.created_at DESC LIMIT 1`,[categoryId,departmentId,companyId||null]);return r[0]||null;}
async function getActiveConfig(assetId,conn=requireDb(),forUpdate=false){let sql='SELECT * FROM asset_depreciation_configs WHERE asset_id=? AND is_active=1 ORDER BY id DESC LIMIT 1';if(forUpdate)sql+=' FOR UPDATE';const [r]=await conn.query(sql,[assetId]);return r[0]||null;}
async function createConfig(data,conn=requireDb()){await conn.query('UPDATE asset_depreciation_configs SET is_active=0 WHERE asset_id=? AND is_active=1',[data.asset_id]);const [r]=await conn.query(`INSERT INTO asset_depreciation_configs (asset_id,depreciation_policy_id,purchase_cost_snapshot,depreciation_method,useful_life_months,salvage_value_type,salvage_value,depreciation_start_date,is_active,created_by) VALUES (?,?,?,?,?,?,?,?,1,?)`,[data.asset_id,data.depreciation_policy_id||null,data.purchase_cost_snapshot,data.depreciation_method,data.useful_life_months,data.salvage_value_type||'FIXED',data.salvage_value||0,data.depreciation_start_date,data.created_by||null]);return r.insertId;}
async function updateConfig(id,data,conn=requireDb()){const fields=['depreciation_policy_id','purchase_cost_snapshot','depreciation_method','useful_life_months','salvage_value_type','salvage_value','depreciation_start_date'];const set=[];const p=[];for(const f of fields){if(data[f]!==undefined){set.push(`${f}=?`);p.push(data[f]);}}if(set.length){p.push(id);await conn.query(`UPDATE asset_depreciation_configs SET ${set.join(',')} WHERE id=?`,p);}}
async function createRevision(data,conn=requireDb()){const [r]=await conn.query(`INSERT INTO asset_depreciation_revisions (asset_id,effective_date,old_values,new_values,reason,changed_by) VALUES (?,?,?,?,?,?)`,[data.asset_id,data.effective_date,JSON.stringify(data.old_values),JSON.stringify(data.new_values),data.reason,data.changed_by]);return r.insertId;}
async function revisions(assetId,conn=requireDb()){const [r]=await conn.query('SELECT * FROM asset_depreciation_revisions WHERE asset_id=? ORDER BY effective_date DESC,id DESC',[assetId]);return r;}
async function ledger(assetId,conn=requireDb()){const [r]=await conn.query('SELECT * FROM asset_depreciation_ledger WHERE asset_id=? ORDER BY period_year,period_month',[assetId]);return r;}
async function lastFinal(assetId,conn=requireDb()){const [r]=await conn.query('SELECT * FROM asset_depreciation_ledger WHERE asset_id=? AND is_final=1 ORDER BY period_year DESC,period_month DESC LIMIT 1',[assetId]);return r[0]||null;}
async function countFinal(assetId,conn=requireDb()){const [[r]]=await conn.query('SELECT COUNT(*) total FROM asset_depreciation_ledger WHERE asset_id=? AND is_final=1',[assetId]);return Number(r.total);}
async function upsertLedger(row,conn=requireDb()){const [existing]=await conn.query('SELECT id,is_final FROM asset_depreciation_ledger WHERE asset_id=? AND period_year=? AND period_month=? LIMIT 1',[row.asset_id,row.period_year,row.period_month]);if(existing[0]?.is_final)return existing[0].id;if(existing[0]){await conn.query(`UPDATE asset_depreciation_ledger SET opening_book_value=?,depreciation_amount=?,accumulated_depreciation=?,closing_book_value=?,calculation_method=?,generated_by=?,generated_at=CURRENT_TIMESTAMP WHERE id=?`,[row.opening_book_value,row.depreciation_amount,row.accumulated_depreciation,row.closing_book_value,row.calculation_method,row.generated_by||null,existing[0].id]);return existing[0].id;}const [r]=await conn.query(`INSERT INTO asset_depreciation_ledger (asset_id,period_year,period_month,opening_book_value,depreciation_amount,accumulated_depreciation,closing_book_value,calculation_method,generated_by) VALUES (?,?,?,?,?,?,?,?,?)`,[row.asset_id,row.period_year,row.period_month,row.opening_book_value,row.depreciation_amount,row.accumulated_depreciation,row.closing_book_value,row.calculation_method,row.generated_by||null]);return r.insertId;}
async function finalize(assetId,year,month,conn=requireDb()){const [r]=await conn.query('UPDATE asset_depreciation_ledger SET is_final=1 WHERE asset_id=? AND period_year=? AND period_month=?',[assetId,year,month]);return r.affectedRows;}
module.exports={listPolicies,getPolicy,createPolicy,updatePolicy,setCategoryDefault,getCategoryDefault,getActiveConfig,createConfig,updateConfig,createRevision,revisions,ledger,lastFinal,countFinal,upsertLedger,finalize};
