const AssetModel=require('../models/asset.model');
const MasterModel=require('../models/master.model');
const PermissionService=require('./permission.service');
const NumberingService=require('./numbering.service');
const ActivityLog=require('./activity-log.service');
const { withTransaction }=require('../utils/db.util');
const { appError }=require('../utils/app-error.util');
const { parsePagination,meta }=require('../utils/pagination.util');
const { diffValues }=require('../utils/diff.util');
const { TRACKING_TYPES,ASSIGNMENT_TYPES,ASSET_CONDITIONS,ASSET_STATUSES }=require('../constants/domain.constants');
const { ACTIVITY_ACTIONS }=require('../constants/activity.constants');
function nowSql(){return new Date();}
async function requireAsset(id,userId,permission,conn,forUpdate=false){const asset=await AssetModel.get(id,conn,forUpdate);if(!asset)throw appError('Asset not found',404,'ASSET_NOT_FOUND');await PermissionService.assertScope(userId,permission,asset.company_id,asset.managing_department_id,conn);return asset;}
async function list(req){const {page,limit,offset}=parsePagination(req.query);const scope=await PermissionService.buildScopeSql(req.user.id,'ASSET_VIEW','a');const data=await AssetModel.list({whereSql:scope.sql,params:scope.params,filters:req.query,limit,offset});return {rows:data.rows,meta:meta(page,limit,data.total)};}
async function get(req){const asset=await requireAsset(req.params.id,req.user.id,'ASSET_VIEW');asset.attributes=await AssetModel.getAttributes(asset.id);asset.assignments=await AssetModel.assignments(asset.id);return asset;}
async function validateCategory(categoryId){const category=await MasterModel.get('categories',categoryId);if(!category)throw appError('Category not found',400,'CATEGORY_NOT_FOUND');if(category.tracking_type!==TRACKING_TYPES.SERIALIZED_ASSET)throw appError('Category is not SERIALIZED_ASSET',400,'INVALID_CATEGORY_TRACKING_TYPE');return category;}
async function create(req){
  const b=req.body; for(const f of ['asset_name','category_id','managing_department_id','company_id'])if(!b[f])throw appError(`${f} is required`,400,'VALIDATION_ERROR');
  await PermissionService.assertScope(req.user.id,'ASSET_CREATE',b.company_id,b.managing_department_id); await validateCategory(b.category_id);if(b.asset_condition&&!Object.values(ASSET_CONDITIONS).includes(b.asset_condition))throw appError('Invalid asset_condition',400,'VALIDATION_ERROR');if(b.status&&!['REGISTERED','AVAILABLE'].includes(b.status))throw appError('Normal asset creation only supports REGISTERED or AVAILABLE status; use lifecycle/assignment operations afterward',400,'INVALID_INITIAL_STATUS');
  const assetNumber=b.asset_number||await NumberingService.generate({departmentId:b.managing_department_id,companyId:b.company_id,sequenceType:'ASSET'});
  const result=await withTransaction(async(conn)=>{const id=await AssetModel.create({...b,asset_number:assetNumber,created_by:req.user.id},conn);await AssetModel.saveAttributes(id,b.category_id,b.attributes||[],conn);await AssetModel.addHistory({asset_id:id,event_type:'CREATED',event_date:nowSql(),description:'Asset created',details:{asset_number:assetNumber},performed_by:req.user.id},conn);const row=await AssetModel.get(id,conn);await ActivityLog.log(req,{module:'ASSET',action:ACTIVITY_ACTIONS.CREATE,entity_type:'ASSET',entity_id:id,entity_reference:assetNumber,entity_name_snapshot:b.asset_name,new_values:row,description:`Created asset ${assetNumber}`},conn);return row;});
  result.attributes=await AssetModel.getAttributes(result.id);return result;
}
async function update(req){return withTransaction(async(conn)=>{const old=await requireAsset(req.params.id,req.user.id,'ASSET_UPDATE',conn,true);for(const f of ['asset_number','managing_department_id','company_id','current_location_id','status','current_assignment_id'])if(req.body[f]!==undefined)throw appError(`${f} cannot be changed through asset update`,400,'USE_BUSINESS_TRANSACTION');if(req.body.category_id!==undefined)await validateCategory(req.body.category_id);await AssetModel.update(old.id,{...req.body,updated_by:req.user.id},conn);const categoryId=req.body.category_id||old.category_id;if(req.body.attributes)await AssetModel.saveAttributes(old.id,categoryId,req.body.attributes,conn);const row=await AssetModel.get(old.id,conn);const diff=diffValues(old,row,['asset_name','category_id','category_name','brand_id','brand_name','model_id','model_name','serial_number','asset_condition','purchase_date','purchase_cost','vendor_id','vendor_name','warranty_until','notes']);if(diff.changed){await AssetModel.addHistory({asset_id:old.id,event_type:'UPDATED',event_date:nowSql(),description:'Asset master updated',details:{changes:diff},performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'ASSET',action:ACTIVITY_ACTIONS.UPDATE,entity_type:'ASSET',entity_id:old.id,entity_reference:old.asset_number,entity_name_snapshot:row.asset_name,old_values:diff.old_values,new_values:diff.new_values,description:`Updated asset ${old.asset_number}`},conn);}return row;});}
function validateAssignmentTarget(b){if(!Object.values(ASSIGNMENT_TYPES).includes(b.assignment_type))throw appError('Invalid assignment_type',400,'VALIDATION_ERROR');if(b.assignment_type==='USER'&&!b.assigned_user_id)throw appError('assigned_user_id is required',400,'VALIDATION_ERROR');if(b.assignment_type==='DEPARTMENT'&&!b.assigned_department_id)throw appError('assigned_department_id is required',400,'VALIDATION_ERROR');if(b.assignment_type==='LOCATION'&&!b.assigned_location_id)throw appError('assigned_location_id is required',400,'VALIDATION_ERROR');}
async function assign(req){return withTransaction(async(conn)=>{const asset=await requireAsset(req.params.id,req.user.id,'ASSET_ASSIGN',conn,true);if(asset.current_assignment_id)throw appError('Asset already has active assignment',409,'ASSET_ALREADY_ASSIGNED');if(['RETIRED','DISPOSED','VOID','LOST'].includes(asset.status))throw appError(`Asset status ${asset.status} cannot be assigned`,400,'ASSET_NOT_ASSIGNABLE');validateAssignmentTarget(req.body);const id=await AssetModel.createAssignment({asset_id:asset.id,...req.body,assigned_at:req.body.assigned_at||nowSql(),assigned_by:req.user.id},conn);const newLocation=req.body.assignment_type==='LOCATION'?req.body.assigned_location_id:asset.current_location_id;await AssetModel.setState(asset.id,{status:'ASSIGNED',current_assignment_id:id,current_location_id:newLocation,updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:'ASSIGNED',event_date:req.body.assigned_at||nowSql(),reference_type:'ASSET_ASSIGNMENT',reference_id:id,description:'Asset assigned',details:req.body,performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'ASSET',action:ACTIVITY_ACTIONS.ASSIGN,entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,entity_name_snapshot:asset.asset_name,new_values:req.body,description:`Assigned asset ${asset.asset_number}`},conn);return AssetModel.getAssignment(id,conn);});}
async function returnAsset(req){return withTransaction(async(conn)=>{const asset=await requireAsset(req.params.id,req.user.id,'ASSET_ASSIGN',conn,true);if(!asset.current_assignment_id)throw appError('Asset has no active assignment',400,'ASSET_NOT_ASSIGNED');const assignment=await AssetModel.getAssignment(asset.current_assignment_id,conn,true);if(!assignment||assignment.returned_at)throw appError('Active assignment not found',409,'ASSIGNMENT_NOT_ACTIVE');if(req.body.return_condition && !Object.values(ASSET_CONDITIONS).includes(req.body.return_condition))throw appError('Invalid return_condition',400,'VALIDATION_ERROR');const returnedAt=req.body.returned_at||nowSql();await AssetModel.closeAssignment(assignment.id,{returned_at:returnedAt,returned_by:req.user.id,return_condition:req.body.return_condition||asset.asset_condition,return_location_id:req.body.return_location_id||asset.current_location_id,return_note:req.body.return_note},conn);await AssetModel.setState(asset.id,{status:'AVAILABLE',current_assignment_id:null,current_location_id:req.body.return_location_id||asset.current_location_id,asset_condition:req.body.return_condition||asset.asset_condition,updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:'RETURNED',event_date:returnedAt,reference_type:'ASSET_ASSIGNMENT',reference_id:assignment.id,description:'Asset returned',details:req.body,performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'ASSET',action:ACTIVITY_ACTIONS.RETURN,entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,entity_name_snapshot:asset.asset_name,old_values:assignment,new_values:req.body,description:`Returned asset ${asset.asset_number}`},conn);return AssetModel.getAssignment(assignment.id,conn);});}
async function transfer(req){return withTransaction(async(conn)=>{const asset=await requireAsset(req.params.id,req.user.id,'ASSET_TRANSFER',conn,true);const toCompany=req.body.to_company_id??asset.company_id,toDept=req.body.to_managing_department_id??asset.managing_department_id,toLocation=req.body.to_location_id??asset.current_location_id;if(String(toCompany)===String(asset.company_id)&&Number(toDept)===Number(asset.managing_department_id)&&Number(toLocation||0)===Number(asset.current_location_id||0))throw appError('Transfer destination is unchanged',400,'NO_TRANSFER_CHANGE');await PermissionService.assertScope(req.user.id,'ASSET_TRANSFER',toCompany,toDept,conn);const date=req.body.transfer_date||nowSql();const id=await AssetModel.createTransfer({asset_id:asset.id,transfer_date:date,from_location_id:asset.current_location_id,to_location_id:toLocation,from_company_id:asset.company_id,to_company_id:toCompany,from_managing_department_id:asset.managing_department_id,to_managing_department_id:toDept,reason:req.body.reason,notes:req.body.notes,transferred_by:req.user.id},conn);await AssetModel.setState(asset.id,{current_location_id:toLocation,company_id:toCompany,managing_department_id:toDept,updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:'TRANSFERRED',event_date:date,reference_type:'ASSET_TRANSFER',reference_id:id,description:'Asset transferred',details:{from:{company_id:asset.company_id,department_id:asset.managing_department_id,location_id:asset.current_location_id},to:{company_id:toCompany,department_id:toDept,location_id:toLocation},reason:req.body.reason},performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'ASSET',action:ACTIVITY_ACTIONS.TRANSFER,entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,entity_name_snapshot:asset.asset_name,old_values:{company_id:asset.company_id,managing_department_id:asset.managing_department_id,current_location_id:asset.current_location_id},new_values:{company_id:toCompany,managing_department_id:toDept,current_location_id:toLocation},description:`Transferred asset ${asset.asset_number}`},conn);return {id,...await AssetModel.get(asset.id,conn)};});}
async function createMaintenance(req){return withTransaction(async(conn)=>{const asset=await requireAsset(req.params.id,req.user.id,'ASSET_MAINTENANCE',conn,true);if(['RETIRED','DISPOSED','VOID'].includes(asset.status))throw appError(`Asset status ${asset.status} cannot enter maintenance`,400,'ASSET_NOT_MAINTAINABLE');if(!req.body.maintenance_type)throw appError('maintenance_type is required',400,'VALIDATION_ERROR');const start=req.body.start_date||nowSql();const id=await AssetModel.createMaintenance({asset_id:asset.id,...req.body,start_date:start,created_by:req.user.id},conn);await AssetModel.setState(asset.id,{status:'MAINTENANCE',updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:'MAINTENANCE_STARTED',event_date:start,reference_type:'ASSET_MAINTENANCE',reference_id:id,description:'Maintenance started',details:req.body,performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'MAINTENANCE',action:ACTIVITY_ACTIONS.MAINTENANCE_CREATE,entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,new_values:req.body,description:`Created maintenance for ${asset.asset_number}`},conn);return AssetModel.getMaintenance(id,conn);});}
async function completeMaintenance(req){return withTransaction(async(conn)=>{const m=await AssetModel.getMaintenance(req.params.maintenanceId,conn,true);if(!m||Number(m.asset_id)!==Number(req.params.id))throw appError('Maintenance not found',404,'MAINTENANCE_NOT_FOUND');const asset=await requireAsset(req.params.id,req.user.id,'ASSET_MAINTENANCE',conn,true);if(m.status==='COMPLETED')throw appError('Maintenance already completed',409,'MAINTENANCE_ALREADY_COMPLETED');const completion=req.body.completion_date||nowSql();await AssetModel.completeMaintenance(m.id,{...req.body,completion_date:completion,completed_by:req.user.id},conn);await AssetModel.setState(asset.id,{status:asset.current_assignment_id?'ASSIGNED':'AVAILABLE',updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:'MAINTENANCE_COMPLETED',event_date:completion,reference_type:'ASSET_MAINTENANCE',reference_id:m.id,description:'Maintenance completed',details:req.body,performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'MAINTENANCE',action:ACTIVITY_ACTIONS.MAINTENANCE_COMPLETE,entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,old_values:m,new_values:req.body,description:`Completed maintenance for ${asset.asset_number}`},conn);return AssetModel.getMaintenance(m.id,conn);});}
async function retire(req){return withTransaction(async(conn)=>{const asset=await requireAsset(req.params.id,req.user.id,'ASSET_RETIRE',conn,true);const status=req.body.status||'RETIRED';if(!['RETIRED','DISPOSED','VOID','LOST'].includes(status))throw appError('Invalid lifecycle terminal status',400,'VALIDATION_ERROR');if(asset.current_assignment_id)throw appError('Return active assignment before changing terminal status',409,'ASSET_HAS_ACTIVE_ASSIGNMENT');await AssetModel.setState(asset.id,{status,updated_by:req.user.id},conn);await AssetModel.addHistory({asset_id:asset.id,event_type:status,event_date:nowSql(),description:req.body.reason||`Asset marked ${status}`,details:req.body,performed_by:req.user.id},conn);await ActivityLog.log(req,{module:'ASSET',action:'LIFECYCLE_UPDATE',entity_type:'ASSET',entity_id:asset.id,entity_reference:asset.asset_number,old_values:{status:asset.status},new_values:{status},description:`Asset ${asset.asset_number} marked ${status}`},conn);return AssetModel.get(asset.id,conn);});}
async function history(req){const asset=await requireAsset(req.params.id,req.user.id,'ASSET_VIEW');return {asset,history:await AssetModel.history(asset.id),assignments:await AssetModel.assignments(asset.id),transfers:await AssetModel.transfers(asset.id),maintenances:await AssetModel.maintenances(asset.id)};}
module.exports={list,get,create,update,assign,returnAsset,transfer,createMaintenance,completeMaintenance,retire,history,requireAsset};
