const ConsumableModel=require('../models/consumable.model');
const MasterModel=require('../models/master.model');
const PermissionService=require('./permission.service');
const NumberingService=require('./numbering.service');
const ActivityLog=require('./activity-log.service');
const config=require('../config');
const { withTransaction }=require('../utils/db.util');
const { appError }=require('../utils/app-error.util');
const { parsePagination,meta }=require('../utils/pagination.util');
const { TRACKING_TYPES,MOVEMENT_TYPES,RECIPIENT_TYPES }=require('../constants/domain.constants');
const { ACTIVITY_ACTIONS }=require('../constants/activity.constants');
function txNumber(){const d=new Date();const stamp=d.toISOString().replace(/[-:TZ.]/g,'').slice(0,14);return `CST-${stamp}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
async function requireConsumable(id,userContext,permission,conn,forUpdate=false){const item=await ConsumableModel.get(id,conn,forUpdate);if(!item)throw appError('Consumable not found',404,'CONSUMABLE_NOT_FOUND');await PermissionService.assertScope(userContext,permission,item.company_id,item.managing_department_id,conn);return item;}
async function validateCategory(id){const category=await MasterModel.get('categories',id);if(!category)throw appError('Category not found',400,'CATEGORY_NOT_FOUND');if(category.tracking_type!==TRACKING_TYPES.CONSUMABLE)throw appError('Category is not CONSUMABLE',400,'INVALID_CATEGORY_TRACKING_TYPE');return category;}
async function list(req){const {page,limit,offset}=parsePagination(req.query);const scope=await PermissionService.buildScopeSql(req.user,'CONSUMABLE_VIEW','c');const data=await ConsumableModel.list({whereSql:scope.sql,params:scope.params,filters:req.query,limit,offset});return {rows:data.rows,meta:meta(page,limit,data.total)};}
async function get(req){const item=await requireConsumable(req.params.id,req.user,'CONSUMABLE_VIEW');item.balances=await ConsumableModel.balances(item.id);return item;}
async function create(req){const b=req.body;for(const f of ['name','category_id','uom_id','managing_department_id','company_id'])if(!b[f])throw appError(`${f} is required`,400,'VALIDATION_ERROR');await PermissionService.assertScope(req.user,'CONSUMABLE_MANAGE',b.company_id,b.managing_department_id);await validateCategory(b.category_id);const code=b.consumable_code||await NumberingService.generate({departmentId:b.managing_department_id,companyId:b.company_id,sequenceType:'CONSUMABLE'});return withTransaction(async(conn)=>{const id=await ConsumableModel.create({...b,consumable_code:code,created_by:req.user.id},conn);const row=await ConsumableModel.get(id,conn);await ActivityLog.log(req,{module:'CONSUMABLE',action:ACTIVITY_ACTIONS.CREATE,entity_type:'CONSUMABLE',entity_id:id,entity_reference:code,entity_name_snapshot:b.name,new_values:row,description:`Created consumable ${code}`},conn);return row;});}
async function update(req){return withTransaction(async(conn)=>{const old=await requireConsumable(req.params.id,req.user,'CONSUMABLE_MANAGE',conn,true);for(const f of ['consumable_code','managing_department_id','company_id'])if(req.body[f]!==undefined)throw appError(`${f} cannot be changed through consumable update`,400,'VALIDATION_ERROR');if(req.body.category_id!==undefined)await validateCategory(req.body.category_id);await ConsumableModel.update(old.id,{...req.body,updated_by:req.user.id},conn);const row=await ConsumableModel.get(old.id,conn);await ActivityLog.log(req,{module:'CONSUMABLE',action:ACTIVITY_ACTIONS.UPDATE,entity_type:'CONSUMABLE',entity_id:old.id,entity_reference:old.consumable_code,entity_name_snapshot:row.name,old_values:old,new_values:row,description:`Updated consumable ${old.consumable_code}`},conn);return row;});}
function permissionForMovement(type){if(['OPENING_BALANCE','RECEIVE','RETURN'].includes(type))return 'CONSUMABLE_RECEIVE';if(type==='ISSUE')return 'CONSUMABLE_ISSUE';if(type==='TRANSFER')return 'CONSUMABLE_TRANSFER';if(type==='ADJUSTMENT')return 'CONSUMABLE_ADJUST';if(type==='WRITE_OFF')return 'CONSUMABLE_WRITE_OFF';return 'CONSUMABLE_MANAGE';}
function validateRecipient(b){if(b.movement_type!=='ISSUE')return;if(!b.recipient_type||!Object.values(RECIPIENT_TYPES).includes(b.recipient_type))throw appError('recipient_type is required for ISSUE',400,'RECIPIENT_REQUIRED');const map={USER:'recipient_user_id',DEPARTMENT:'recipient_department_id',ASSET:'recipient_asset_id',LOCATION:'recipient_location_id'};const field=map[b.recipient_type];if(field&&!b[field])throw appError(`${field} is required for recipient_type ${b.recipient_type}`,400,'RECIPIENT_REQUIRED');}
function requiredLocations(b){if(['ISSUE','WRITE_OFF'].includes(b.movement_type)&&!b.from_location_id)throw appError('from_location_id is required',400,'VALIDATION_ERROR');if(['OPENING_BALANCE','RECEIVE','RETURN'].includes(b.movement_type)&&!b.to_location_id)throw appError('to_location_id is required',400,'VALIDATION_ERROR');if(b.movement_type==='TRANSFER'&&(!b.from_location_id||!b.to_location_id))throw appError('from_location_id and to_location_id are required',400,'VALIDATION_ERROR');if(b.movement_type==='ADJUSTMENT'&&!b.to_location_id)throw appError('to_location_id is required for ADJUSTMENT',400,'VALIDATION_ERROR');}
async function move(req){const b=req.body;if(!Object.values(MOVEMENT_TYPES).includes(b.movement_type))throw appError('Invalid movement_type',400,'VALIDATION_ERROR');const qty=Number(b.quantity);if(!Number.isFinite(qty)||qty===0)throw appError('quantity must be a non-zero number',400,'VALIDATION_ERROR');if(b.movement_type!=='ADJUSTMENT'&&qty<0)throw appError('quantity must be positive except ADJUSTMENT',400,'VALIDATION_ERROR');requiredLocations(b);validateRecipient(b);const perm=permissionForMovement(b.movement_type);
  return withTransaction(async(conn)=>{const item=await requireConsumable(req.params.id,req.user,perm,conn,true);const changes=[];
    async function apply(locationId,delta){const bal=await ConsumableModel.lockBalance(item.id,locationId,conn);const next=Number(bal.quantity)+Number(delta);if(!config.consumable.allowNegativeStock&&next<0)throw appError('Insufficient consumable stock',409,'INSUFFICIENT_STOCK',{location_id:locationId,current_quantity:bal.quantity,requested_delta:delta});await ConsumableModel.setBalance(item.id,locationId,next,conn);changes.push({location_id:locationId,old_quantity:Number(bal.quantity),new_quantity:next});}
    if(['ISSUE','WRITE_OFF'].includes(b.movement_type))await apply(b.from_location_id,-qty);
    else if(['OPENING_BALANCE','RECEIVE','RETURN'].includes(b.movement_type))await apply(b.to_location_id,qty);
    else if(b.movement_type==='TRANSFER'){if(Number(b.from_location_id)===Number(b.to_location_id))throw appError('Transfer locations must differ',400,'VALIDATION_ERROR');await apply(b.from_location_id,-qty);await apply(b.to_location_id,qty);}
    else if(b.movement_type==='ADJUSTMENT')await apply(b.to_location_id,qty);
    const id=await ConsumableModel.createTransaction({...b,quantity:qty,consumable_id:item.id,transaction_number:txNumber(),transaction_date:b.transaction_date||new Date(),created_by:req.user.id},conn);const action={OPENING_BALANCE:'RECEIVE',RECEIVE:'RECEIVE',RETURN:'RECEIVE',ISSUE:'ISSUE',TRANSFER:'TRANSFER',ADJUSTMENT:'ADJUST',WRITE_OFF:'WRITE_OFF'}[b.movement_type]||b.movement_type;await ActivityLog.log(req,{module:'CONSUMABLE_STOCK',action,entity_type:'CONSUMABLE',entity_id:item.id,entity_reference:item.consumable_code,entity_name_snapshot:item.name,old_values:changes.map((x)=>({location_id:x.location_id,quantity:x.old_quantity})),new_values:{movement:b,balances:changes.map((x)=>({location_id:x.location_id,quantity:x.new_quantity}))},description:`${b.movement_type} ${qty} ${item.uom_code||''} ${item.consumable_code}`},conn);return ConsumableModel.getTransaction(id,conn);});}
async function history(req){const item=await requireConsumable(req.params.id,req.user,'CONSUMABLE_VIEW');return {consumable:item,balances:await ConsumableModel.balances(item.id),transactions:await ConsumableModel.transactions(item.id)};}
module.exports={list,get,create,update,move,history,requireConsumable,permissionForMovement};
