const XLSX=require('xlsx');
const PermissionService=require('./permission.service');
const ActivityLog=require('./activity-log.service');
const ExportModel=require('../models/export.model');
const { requireDb }=require('../utils/db.util');
const { appError }=require('../utils/app-error.util');
const { ACTIVITY_ACTIONS }=require('../constants/activity.constants');
function exportNumber(){const d=new Date();const stamp=d.toISOString().replace(/[-:TZ.]/g,'').slice(0,14);return `EXP-${stamp}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
async function queryScoped(type,userId,query){const db=requireDb();let permission='EXPORT_DATA',scopePermission='ASSET_VIEW',alias='a',dept='managing_department_id',company='company_id',sql='';const params=[];
  if(type==='ASSET_LIST'){scopePermission='ASSET_REPORT';sql=`SELECT a.asset_number,a.asset_name,c.name category,b.name brand,m.name model,a.serial_number,a.managing_department_id,a.company_id,l.name location,a.status,a.asset_condition,a.purchase_date,a.purchase_cost,v.name vendor,a.warranty_until FROM assets a JOIN master_categories c ON c.id=a.category_id LEFT JOIN master_brands b ON b.id=a.brand_id LEFT JOIN master_models m ON m.id=a.model_id LEFT JOIN master_locations l ON l.id=a.current_location_id LEFT JOIN master_vendors v ON v.id=a.vendor_id WHERE __SCOPE__ ORDER BY a.asset_number`;}
  else if(type==='ASSIGNMENTS'){scopePermission='ASSET_REPORT';sql=`SELECT a.asset_number,a.asset_name,x.assignment_type,x.assigned_user_id,x.assigned_user_name_snapshot,x.assigned_department_id,x.assigned_department_name_snapshot,x.assigned_location_id,x.assigned_location_name_snapshot,x.assigned_at,x.returned_at,x.return_condition,x.return_note FROM asset_assignments x JOIN assets a ON a.id=x.asset_id WHERE __SCOPE__ ORDER BY x.assigned_at DESC`;}
  else if(type==='TRANSFERS'){scopePermission='ASSET_REPORT';sql=`SELECT a.asset_number,a.asset_name,x.transfer_date,x.from_location_id,x.to_location_id,x.from_company_id,x.to_company_id,x.from_managing_department_id,x.to_managing_department_id,x.reason,x.notes FROM asset_transfers x JOIN assets a ON a.id=x.asset_id WHERE __SCOPE__ ORDER BY x.transfer_date DESC`;}
  else if(type==='MAINTENANCE'){scopePermission='ASSET_REPORT';sql=`SELECT a.asset_number,a.asset_name,x.maintenance_type,v.name vendor,x.start_date,x.completion_date,x.cost,x.problem_description,x.result,x.status,x.notes FROM asset_maintenances x JOIN assets a ON a.id=x.asset_id LEFT JOIN master_vendors v ON v.id=x.vendor_id WHERE __SCOPE__ ORDER BY x.start_date DESC`;}
  else if(type==='DEPRECIATION'){scopePermission='DEPRECIATION_VIEW';sql=`SELECT a.asset_number,a.asset_name,a.managing_department_id,a.company_id,d.period_year,d.period_month,d.opening_book_value,d.depreciation_amount,d.accumulated_depreciation,d.closing_book_value,d.calculation_method,d.is_final FROM asset_depreciation_ledger d JOIN assets a ON a.id=d.asset_id WHERE __SCOPE__ ORDER BY a.asset_number,d.period_year,d.period_month`;}
  else if(type==='CONSUMABLE_STOCK'){scopePermission='CONSUMABLE_REPORT';alias='c';sql=`SELECT c.consumable_code,c.name,c.managing_department_id,c.company_id,l.code location_code,l.name location,b.quantity,u.code uom_code,c.minimum_stock FROM consumable_stock_balances b JOIN consumables c ON c.id=b.consumable_id JOIN master_locations l ON l.id=b.location_id JOIN master_uoms u ON u.id=c.uom_id WHERE __SCOPE__ ORDER BY c.consumable_code,l.name`;}
  else if(type==='CONSUMABLE_MOVEMENTS'||type==='CONSUMABLE_USAGE'){scopePermission='CONSUMABLE_REPORT';alias='c';sql=`SELECT c.consumable_code,c.name,c.managing_department_id,c.company_id,t.transaction_number,t.movement_type,t.transaction_date,t.from_location_id,t.to_location_id,t.quantity,t.unit_cost,t.recipient_type,t.recipient_user_id,t.recipient_user_name_snapshot,t.recipient_department_id,t.recipient_department_name_snapshot,t.recipient_asset_id,t.recipient_location_id,t.purpose,t.reference_number FROM consumable_stock_transactions t JOIN consumables c ON c.id=t.consumable_id WHERE __SCOPE__ ${type==='CONSUMABLE_USAGE'?"AND t.movement_type='ISSUE'":''} ORDER BY t.transaction_date DESC`;}
  else if(type==='ACTIVITY_LOG'){await PermissionService.assertAny(userId,'ACTIVITY_LOG_EXPORT');scopePermission='ACTIVITY_LOG_VIEW';alias='a';dept='department_id_snapshot';company='company_id_snapshot';sql=`SELECT a.* FROM activity_logs a WHERE __SCOPE__ ORDER BY a.created_at DESC`;}
  else throw appError('Unsupported export type',400,'EXPORT_TYPE_NOT_SUPPORTED');
  await PermissionService.assertAny(userId,permission);const scope=await PermissionService.buildScopeSql(userId,scopePermission,alias,dept,company);sql=sql.replace('__SCOPE__',scope.sql);const [rows]=await db.query(sql,[...scope.params,...params]);return {rows,scope};}
async function generate(req){const type=String(req.params.type||'').toUpperCase();const {rows,scope}=await queryScoped(type,req.user.id,req.query);const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Data');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});const number=exportNumber();const filename=`asset-${type.toLowerCase()}-${number}.xlsx`;await ExportModel.insert({export_number:number,export_type:type,filters:req.query,scope_snapshot:scope.grants,row_count:rows.length,filename,created_by:req.user.id});await ActivityLog.log(req,{module:'EXPORT',action:ACTIVITY_ACTIONS.EXPORT,entity_type:'EXPORT',entity_reference:number,new_values:{export_type:type,row_count:rows.length,filters:req.query},description:`Exported ${type} (${rows.length} rows)`});return {buffer,filename,row_count:rows.length};}
module.exports={generate};
