CREATE TABLE IF NOT EXISTS export_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  export_number VARCHAR(100) NOT NULL,
  export_type VARCHAR(80) NOT NULL,
  format VARCHAR(20) NOT NULL DEFAULT 'XLSX',
  filters JSON NULL,
  scope_snapshot JSON NULL,
  row_count INT UNSIGNED NOT NULL DEFAULT 0,
  filename VARCHAR(255) NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_export_history_number (export_number),
  KEY idx_export_history_user (created_by, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id CHAR(36) NULL,
  username_snapshot VARCHAR(180) NULL,
  user_name_snapshot VARCHAR(180) NULL,
  department_id_snapshot BIGINT UNSIGNED NULL,
  department_name_snapshot VARCHAR(180) NULL,
  company_id_snapshot VARCHAR(64) NULL,
  company_name_snapshot VARCHAR(180) NULL,
  module VARCHAR(80) NOT NULL,
  action VARCHAR(100) NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'APPLICATION',
  correlation_id CHAR(36) NULL,
  entity_type VARCHAR(80) NULL,
  entity_id BIGINT UNSIGNED NULL,
  entity_reference VARCHAR(180) NULL,
  entity_name_snapshot VARCHAR(255) NULL,
  description VARCHAR(500) NULL,
  old_values JSON NULL,
  new_values JSON NULL,
  ip_address VARCHAR(80) NULL,
  user_agent VARCHAR(500) NULL,
  request_method VARCHAR(20) NULL,
  request_path VARCHAR(500) NULL,
  status ENUM('SUCCESS','FAILED') NOT NULL DEFAULT 'SUCCESS',
  error_message VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_activity_logs_user (user_id, created_at),
  KEY idx_activity_logs_entity (entity_type, entity_id, created_at),
  KEY idx_activity_logs_module_action (module, action, created_at),
  KEY idx_activity_logs_correlation (correlation_id, created_at),
  KEY idx_activity_logs_source (source, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
